

/* First created by JCasGen Fri Dec 09 22:50:50 EST 2016 */
package cz.brmlab.yodaqa.model.CandidateAnswer;

import org.apache.uima.jcas.JCas; 
import org.apache.uima.jcas.JCasRegistry;
import org.apache.uima.jcas.cas.TOP_Type;

import org.apache.uima.jcas.cas.TOP;


/** A feature matched on this answer. This type is for sub-classing to particular features.
 * Updated by JCasGen Fri Dec 09 22:50:50 EST 2016
 * XML source: /home/leo/SourceTree3dParty/yodaqa-1.6/src/main/typesystem/SearchResultTypes_TS.xml
 * @generated */
public class AnswerFeature extends TOP {
  /** @generated
   * @ordered 
   */
  @SuppressWarnings ("hiding")
  public final static int typeIndexID = JCasRegistry.register(AnswerFeature.class);
  /** @generated
   * @ordered 
   */
  @SuppressWarnings ("hiding")
  public final static int type = typeIndexID;
  /** @generated
   * @return index of the type  
   */
  @Override
  public              int getTypeIndexID() {return typeIndexID;}
 
  /** Never called.  Disable default constructor
   * @generated */
  protected AnswerFeature() {/* intentionally empty block */}
    
  /** Internal - constructor used by generator 
   * @generated
   * @param addr low level Feature Structure reference
   * @param type the type of this Feature Structure 
   */
  public AnswerFeature(int addr, TOP_Type type) {
    super(addr, type);
    readObject();
  }
  
  /** @generated
   * @param jcas JCas to which this Feature Structure belongs 
   */
  public AnswerFeature(JCas jcas) {
    super(jcas);
    readObject();   
  } 

  /** 
   * <!-- begin-user-doc -->
   * Write your own initialization here
   * <!-- end-user-doc -->
   *
   * @generated modifiable 
   */
  private void readObject() {/*default - does nothing empty block */}
     
 
    
  //*--------------*
  //* Feature: name

  /** getter for name - gets Feature name.  Always refer to the names via string constants in the ansscore.AF class to prevent typos.  Some feature names may be autogenerated (e.g. specific LAT/SV presence indicators or vector embedding elements).
   * @generated
   * @return value of the feature 
   */
  public String getName() {
    if (AnswerFeature_Type.featOkTst && ((AnswerFeature_Type)jcasType).casFeat_name == null)
      jcasType.jcas.throwFeatMissing("name", "cz.brmlab.yodaqa.model.CandidateAnswer.AnswerFeature");
    return jcasType.ll_cas.ll_getStringValue(addr, ((AnswerFeature_Type)jcasType).casFeatCode_name);}
    
  /** setter for name - sets Feature name.  Always refer to the names via string constants in the ansscore.AF class to prevent typos.  Some feature names may be autogenerated (e.g. specific LAT/SV presence indicators or vector embedding elements). 
   * @generated
   * @param v value to set into the feature 
   */
  public void setName(String v) {
    if (AnswerFeature_Type.featOkTst && ((AnswerFeature_Type)jcasType).casFeat_name == null)
      jcasType.jcas.throwFeatMissing("name", "cz.brmlab.yodaqa.model.CandidateAnswer.AnswerFeature");
    jcasType.ll_cas.ll_setStringValue(addr, ((AnswerFeature_Type)jcasType).casFeatCode_name, v);}    
   
    
  //*--------------*
  //* Feature: value

  /** getter for value - gets Feature value. Unmatched features are assumed 0. Ideally, the feature value should be in the interval of [0,1], but this is not enforced.
   * @generated
   * @return value of the feature 
   */
  public double getValue() {
    if (AnswerFeature_Type.featOkTst && ((AnswerFeature_Type)jcasType).casFeat_value == null)
      jcasType.jcas.throwFeatMissing("value", "cz.brmlab.yodaqa.model.CandidateAnswer.AnswerFeature");
    return jcasType.ll_cas.ll_getDoubleValue(addr, ((AnswerFeature_Type)jcasType).casFeatCode_value);}
    
  /** setter for value - sets Feature value. Unmatched features are assumed 0. Ideally, the feature value should be in the interval of [0,1], but this is not enforced. 
   * @generated
   * @param v value to set into the feature 
   */
  public void setValue(double v) {
    if (AnswerFeature_Type.featOkTst && ((AnswerFeature_Type)jcasType).casFeat_value == null)
      jcasType.jcas.throwFeatMissing("value", "cz.brmlab.yodaqa.model.CandidateAnswer.AnswerFeature");
    jcasType.ll_cas.ll_setDoubleValue(addr, ((AnswerFeature_Type)jcasType).casFeatCode_value, v);}    
  }

    